@startuml
'https://plantuml.com/class-diagram

class WBCell {
}

class WBCell4P{
}

class WBCell5P{
}

WBCell4P --|> WBCell

WBCell5P --|> WBCell

class WBTessellation {

}

WBTessellation --> WBCell: cell_spec >

class FETriangularMesh{
}

class WBShellGeometry{
}

WBShellGeometry --|> WBTessellation

WBShellGeometry <.. FETriangularMesh : geo <


class TModel{
    get_corr_pred()
}

class XModel{
    field_mappings()
}

class TriXDomainFE{
}

XDomainFE --|> XModel
TriXDomainFE --|> XDomainFE

TriXDomainFE --> FETriangularMesh : mesh >

WBShellAnalysis --> WBShellGeometry : geo >
WBShellAnalysis --> TModel : tmodel >
WBShellAnalysis --> TriXDomainFE : xmodel >

@enduml