@startuml
'https://plantuml.com/class-diagram

class WBCell {
}

class WBCell4P{
}

class WBCell5P{
}

WBCell4P --|> WBCell

WBCell5P --|> WBCell

class WBTessellation {

}

WBTessellation --> WBCell: cell_spec >

class WBFETriangularMesh{
}

class WBShellGeometry{
}

WBShellGeometry --|> WBTessellation

WBShellGeometry <.. WBFETriangularMesh : geo <


class TModel{
    get_corr_pred()
}

class XModel{
    field_mappings()
}

class WBXDomainFE{
}

XDomainFE --|> XModel
WBXDomainFE --|> XDomainFE

WBXDomainFE --> WBFETriangularMesh : mesh >

WBShellAnalysis --> WBShellGeometry : geo >
WBShellAnalysis --> TModel : tmodel >
WBShellAnalysis --> WBXDomainFE : xmodel >

@enduml