@startuml
'https://plantuml.com/class-diagram

class WBCell {
}

class WBTessellation {

}

WBTessellation --> WBCell

class FETriangularMesh{
}

class WBShellFETriangularMesh{
}

WBShellFETriangularMesh --|> WBTessellation

WBShellFETriangularMesh --|> FETriangularMesh


class TModel{
    get_corr_pred()
}

class XModel{
    field_mappings()
}

class WBXDomainFE{
}

XDomainFE --|> XModel
WBXDomainFE --|> XDomainFE

WBXDomainFE --> WBShellFETriangularMesh

WBModel ..> WBShellFETriangularMesh
WBModel --> TModel
WBModel --> WBXDomainFE

@enduml